apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-certificate
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
      cert-utils-operator.redhat-cop.io/generate-java-keystores: "true"
  secretName: sample-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - org
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'ivia-wrp-ibm-verify.apps.itz-jsmlpv.infra01-lb.lon04.techzone.ibm.com'
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: pkcs12-pass
        key: password
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
